# Change tunnel and credentials-file values depending on host machine
# run the following commands to link this config file to cloudflared service config location
# sudo rm /etc/cloudflared/config.yml
# sudo ln -s /home/jaeho/marvin/app/server/config.yml /etc/cloudflared/config.yml
tunnel: ceb2c9a8-4565-41b9-bf99-8b38a579e55b
credentials-file: /home/jaeho/.cloudflared/ceb2c9a8-4565-41b9-bf99-8b38a579e55b.json

ingress:
  - hostname: cvat.jaehho.com
    service: http://localhost:8080
  - hostname: marvin-rosbridge.jaehho.com
    service: http://localhost:9090
  - service: http_status:404