# Default initial positions for marvin's ros2_control fake system

initial_positions:
  left_gripper: 0
  left_joint1: 0
  left_joint2: 0
  left_joint3: 0
  left_joint4: 0
  right_gripper: 0
  right_joint1: 0
  right_joint2: 0
  right_joint3: 0
  right_joint4: 0